server:
  port: 10001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:10001

  client:
    service-url:
      defaultZone: http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/
spring:
  application:
    name: Eureka
