server:
  port: 10003
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:10003
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/
spring:
  application:
    name: Eureka

